x-rulesets: [ base, documentation, ai-ready ]
functions:
  - uniquenessTags
functionsDir: "../../functions"
rules:
  openapi-tags-uniqueness:
    description: Названия тегов должны быть уникальными
    documentationUrl: https://gitlabci.raiffeisen.ru/cib/api-guide/-/tree/master/spectral/rules/openapi?ref_type=heads#openapi-tags-uniqueness
    severity: error
    resolved: false
    given: '$.tags'
    then:
      function: uniquenessTags